before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: hfVxZHkuvtq1pkEfBYQ3gz5AFkBweO8/WE2AZK+QKcatUcbiaIhmfRGopdB+bl+OIOqmh6skve4E4nDQXIrbikbkrI2gBiXSB4hgSio8o80voUASbGnkZ/yuK9jOJjXWGUXub4zlXxjpXSGt+zxv0N38aTljzGHblOKiDTpUdFwdzMTM5lKJgqjCv9t4//Nvb4HgTDCAOr25qw8N3DNZp+A4bBsv2xpRVmO5f8yMNpab7F6i00/lRCghIP3af8zoWHwZhiiWxDgD7p6GZmwUdwee/ubpsNOhkW7vHLxSH9LF9LJMsFiK27NdS496UAgPUkpk1+55T3EtxnFwcXzMoBBGJGADdZOGAS7BSyeiz137w1o8UywDbZZwdV1XSsAiqgxjOcGLD1C7MX+rp3CCIbQMIgd/YQbLIs500kOX2nGpFZ8Vz3xj1DZvJXgdURs9+Jho/mKPuCtm2/yz6exd5RSl6OosNGwbxd2SdDip02uPthG3/sOpgo37KKvHwHU56DSHSkODEwfgZ1Kumht71PiU3+/63f4IB6gNOk9XaYQot1LJmhgdUfgTkcijttwCem2r4ZwLtt8L0sR0aK1/VxbJLGYEb7Fv5OLjAFI0JayVIgAd+NaqD74H2xPMhm4ANK6ebMKzjS28oKK1cGdJ23bKSxcjWwEeLvWtlXc3/fk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
